version: "3.9"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    restart: always
    ports:
      - "3000:3000"
    env_file: ./docker_env/server.env
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:latest
    container_name: database_nienluan1
    restart: always
    env_file:
      - ./docker_env/mysql.env
    ports:
      - "3309:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./database/backup.sql:/docker-entrypoint-initdb.d/backup.sql
  redis:
    image: redis:latest
    container_name: redis_nienluan
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
