version: "3.9"
services:
  mysql:
    image: mysql:latest
    container_name: database_nienluan
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nienlu@nNganhY2023
      MYSQL_DATABASE: db_nienluan
      MYSQL_USER: nienluan
      MYSQL_PASSWORD: nienlu@n2023
    ports:
      - 3307:3306
    volumes:
      - ./mysql:/var/lib/mysql
  redis:
    image: redis:latest
    container_name: redis_nienluan
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
