version: "3.3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
    depends_on:
      - server
  server:
    image: caophuoclongse/nienluan_server:latest
    container_name: server
    restart: always
    ports:
      - "3070:3003"
    env_file: ./docker_env/server.env
    volumes:
      - ./public:/app/public
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:latest
    container_name: database_nienluan1
    restart: always
    env_file:
      - ./docker_env/mysql.env
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./database/backup.sql:/docker-entrypoint-initdb.d/backup.sql
  redis:
    image: redis:latest
    container_name: redis_nienluan
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
